apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-mongo
  template:
    metadata:
      labels:
        app: users-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: users
---
apiVersion: v1
kind: Service
metadata:
  name: users-mongo-srv
spec:
  selector:
    app: users-mongo
  ports:
    - port: 27017
      targetPort: 27017